const CARRIERS=[{id:"DHL",color:"#d5a900"},{id:"DPD",color:"#ca2034"},{id:"GLS",color:"#153a6b"},{id:"Hermes",color:"#184f91"},{id:"UPS",color:"#5b3a23"},{id:"Amazon",color:"#263746"},{id:"FedEx",color:"#5d2d91"}];
const STORE="parcelflow_packages_v1";let packages=load();let carrier="DHL",pendingPickup=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function load(){try{return JSON.parse(localStorage.getItem(STORE))||[]}catch{return[]}}
function save(){localStorage.setItem(STORE,JSON.stringify(packages));renderAll()}
function esc(v){const d=document.createElement("div");d.textContent=String(v??"");return d.innerHTML}
function date(v){return new Intl.DateTimeFormat("de-DE",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(v))}
function today(v){return new Date(v).toDateString()===new Date().toDateString()}
function toast(msg){const t=$("#toast");t.textContent=msg;t.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove("show"),3000)}
function nextSlot(zone=$("#zone")?.value||"HERMES"){const used=new Set(packages.filter(p=>p.status==="stored").map(p=>p.slot));for(let i=1;i<=500;i++){const s=`${zone}-${String(i).padStart(3,"0")}`;if(!used.has(s))return s}return "VOLL"}
function go(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===id));const names={dashboard:["PAKETSHOP","Guten Tag"],intake:["PAKETANNAHME","Neues Paket"],inventory:["LAGERWIRTSCHAFT","Lagerbestand"],pickup:["PAKETAUSGABE","Abholung"],settings:["VERWALTUNG","Einstellungen"]};$("#pageEyebrow").textContent=names[id][0];$("#pageTitle").textContent=names[id][1];$(".sidebar").classList.remove("open");if(id==="pickup")renderPickup("");scrollTo(0,0)}
function renderCarriers(){const html=CARRIERS.map(c=>`<button type="button" class="carrier-option ${c.id===carrier?'active':''}" data-carrier="${c.id}">${c.id}</button>`).join("");$("#carrierPicker").innerHTML=html;$("#carrierFilter").innerHTML='<option value="">Alle Paketdienste</option>'+CARRIERS.map(c=>`<option>${c.id}</option>`).join("")}
function carrierBadge(c){const x=CARRIERS.find(v=>v.id===c)||CARRIERS[0];return `<span class="carrier-badge" style="background:${x.color}">${esc(c)}</span>`}
function renderDashboard(){const active=packages.filter(p=>p.status==="stored"),picked=packages.filter(p=>p.status==="picked"&&today(p.pickedAt));$("#metricToday").textContent=packages.filter(p=>today(p.createdAt)).length;$("#metricStored").textContent=active.length;$("#metricPicked").textContent=picked.length;$("#metricOverdue").textContent=active.filter(p=>Date.now()-new Date(p.createdAt)>6048e5).length;const cap=Math.round(active.length/15);$("#capacityText").textContent=`${cap} % belegt`;$("#capacityBar").style.width=`${Math.min(cap,100)}%`;$("#recentList").innerHTML=packages.slice().sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).slice(0,5).map(p=>`<div class="package-row">${carrierBadge(p.carrier)}<div><strong>${esc(p.firstName+' '+p.lastName)}</strong><small>${esc(p.carrier)} · ${esc(p.tracking)}</small></div><div class="slot">${esc(p.slot)}</div></div>`).join("")||'<div class="empty">Noch keine Pakete erfasst.</div>';const max=Math.max(1,...CARRIERS.map(c=>active.filter(p=>p.carrier===c.id).length));$("#carrierChart").innerHTML=CARRIERS.map(c=>{const n=active.filter(p=>p.carrier===c.id).length;return `<div class="carrier-line"><span>${c.id}</span><i><b style="width:${n/max*100}%;background:${c.color}"></b></i><strong>${n}</strong></div>`}).join("")}
function filtered(){const q=$("#inventorySearch").value.trim().toLowerCase(),c=$("#carrierFilter").value,s=$("#statusFilter").value;return packages.filter(p=>(!c||p.carrier===c)&&(!s||p.status===s)&&(!q||Object.values(p).some(v=>String(v).toLowerCase().includes(q))))}
function renderInventory(){const list=filtered().sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));$("#inventoryBody").innerHTML=list.map(p=>`<tr><td><strong class="slot">${esc(p.slot)}</strong></td><td><strong>${esc(p.firstName+' '+p.lastName)}</strong><small>${esc([p.street,p.houseNo,p.zip,p.city].filter(Boolean).join(' '))}</small></td><td>${carrierBadge(p.carrier)}</td><td>${esc(p.tracking)}</td><td>${date(p.createdAt)}</td><td><span class="status-badge ${p.status}">${p.status==='stored'?'Eingelagert':'Abgeholt'}</span></td><td>${p.status==='stored'?`<button class="action-btn" data-pick="${p.id}">Ausgeben</button>`:''}</td></tr>`).join("");$("#inventoryEmpty").classList.toggle("hidden",!!list.length)}
function renderPickup(q){q=q.trim().toLowerCase();const list=packages.filter(p=>p.status==="stored"&&(!q||[p.tracking,p.slot,p.firstName,p.lastName,p.carrier].some(v=>String(v).toLowerCase().includes(q))));$("#pickupResults").innerHTML=list.slice(0,12).map(p=>`<article class="pickup-card"><div class="slot">${esc(p.slot)}</div><h3>${esc(p.firstName+' '+p.lastName)}</h3><p>${esc(p.carrier)} · ${esc(p.tracking)}<br>Eingang: ${date(p.createdAt)}</p><button class="primary full" data-pick="${p.id}">Paket ausgeben</button></article>`).join("")||(q?'<div class="empty">Kein eingelagertes Paket gefunden.</div>':'<div class="empty">Suchbegriff eingeben oder Paket auswählen.</div>')}
function askPickup(id){const p=packages.find(x=>x.id===id);if(!p)return;pendingPickup=id;$("#dialogTitle").textContent=`Lagerplatz ${p.slot} ausgeben?`;$("#dialogText").textContent=`${p.firstName} ${p.lastName} · ${p.carrier} · ${p.tracking}`;$("#confirmDialog").showModal()}
function renderAll(){renderDashboard();renderInventory();$("#nextSlot").textContent=nextSlot()}
$("#intakeForm").addEventListener("submit",e=>{e.preventDefault();const slot=nextSlot(),storageLocation=$("#zone").value;if(slot==="VOLL")return toast("Der gewählte Lagerort ist vollständig belegt.");const p={id:crypto.randomUUID(),carrier,storageLocation,tracking:$("#tracking").value.trim(),firstName:$("#firstName").value.trim(),lastName:$("#lastName").value.trim(),street:$("#street").value.trim(),houseNo:$("#houseNo").value.trim(),zip:$("#zip").value.trim(),city:$("#city").value.trim(),notes:$("#notes").value.trim(),slot,status:"stored",createdAt:new Date().toISOString(),pickedAt:null};if(packages.some(x=>x.tracking===p.tracking&&x.status==='stored'))return toast("Diese Sendungsnummer ist bereits eingelagert.");packages.unshift(p);save();e.target.reset();carrier="DHL";renderCarriers();$("#nextSlot").textContent=nextSlot();toast(`Paket erfolgreich auf ${slot} eingelagert.`);go("dashboard")});
$("#intakeForm").addEventListener("reset",()=>setTimeout(()=>{$("#nextSlot").textContent=nextSlot()},0));$("#zone").addEventListener("change",()=>$("#nextSlot").textContent=nextSlot());
document.addEventListener("click",e=>{const c=e.target.closest("[data-carrier]"),g=e.target.closest("[data-go]"),p=e.target.closest("[data-pick]");if(c){carrier=c.dataset.carrier;renderCarriers()}if(g)go(g.dataset.go);if(p)askPickup(p.dataset.pick)});$$('.nav-item').forEach(b=>b.onclick=()=>go(b.dataset.view));
[$("#inventorySearch"),$("#carrierFilter"),$("#statusFilter")].forEach(x=>x.addEventListener("input",renderInventory));$("#pickupSearch").addEventListener("input",e=>renderPickup(e.target.value));$("#globalSearch").addEventListener("keydown",e=>{if(e.key==='Enter'){go('inventory');$("#inventorySearch").value=e.target.value;renderInventory()}});$("#scanBtn").onclick=()=>{toast("Sendungsnummer mit Scanner erfassen oder direkt eingeben.");$("#tracking").focus()};$("#menuBtn").onclick=()=>$(".sidebar").classList.toggle("open");
$("#cancelDialog").onclick=()=>$("#confirmDialog").close();$("#confirmPickup").onclick=()=>{const p=packages.find(x=>x.id===pendingPickup);if(p){p.status="picked";p.pickedAt=new Date().toISOString();save();renderPickup($("#pickupSearch").value);toast(`Paket ${p.slot} erfolgreich ausgegeben.`)}$("#confirmDialog").close()};
$("#exportBtn").onclick=()=>{const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),packages},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`parcelflow-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);toast("Backup wurde erstellt.")};$("#importInput").onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(!Array.isArray(data.packages))throw 0;packages=data.packages;save();toast(`${packages.length} Pakete wurden importiert.`)}catch{toast("Backup konnte nicht gelesen werden.")}e.target.value=""};
renderCarriers();renderAll();
